mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('notp/', include('notp.urls', namespace='notp')),
    path('admin/', admin.site.urls),
]

mysite/notp/urls.py
from django.urls import path
from . import views

app_name = 'notp'
urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('search/', views.SearchResultView.as_view(), name='searchresult'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('moreitems/', views.MoreItemsView.as_view(), name='moreitems'),
    path('form/', views.form, name='form'),
]

mysite/notp/models.py
import django.utils.timezone

# from django.contrib.gis.db import models
from django.contrib.gis.db import models

from django.db import models

# Create your models here.
class Donor(models.Model):
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    quantity = models.PositiveIntegerField(default=0)
    zipcode = models.PositiveIntegerField(default = 0)
    latitude = models.DecimalField(max_digits=8, decimal_places=6)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    # location = django.contrib.gis.db.models.PointField(null=False, blank=False, srid=4326, verbose_name="Location")
    join_date = models.DateTimeField('date joined', default=django.utils.timezone.now)
    points = models.PositiveIntegerField(default=0)
    status = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.id

    def valid(self):
        return self.quantity > 0

class Recipient(models.Model):
    name = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=200, blank=True)
    request = models.IntegerField(default=1)
    zipcode = models.PositiveIntegerField(default = 0)
    latitude = models.DecimalField(max_digits=8, decimal_places=6, default=0)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, default=0)
    # location = django.contrib.gis.db.models.PointField(null=False, blank=False, srid=4326, verbose_name="Location")
    join_date = models.DateTimeField('date joined', default=django.utils.timezone.now)
    # donor = models.ForeignKey(Donor, on_delete=models.CASCADE)

    def __str__(self):
        return self.id

mysite/notp/views.py
# from django.contrib.gis.geos import *
# from django.contrib.gis.measure import D
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.db.models import Q
from geopy.distance import geodesic
from uszipcode import SearchEngine
from .models import Donor, Recipient

search = SearchEngine(simple_zipcode=True)

class IndexView(generic.TemplateView): 
    template_name = 'notp/index.html'

class SearchResultView(generic.ListView):
    model = Donor
    template_name = 'notp/searchresult.html'

    def get_queryset(self):
        query = self.request.GET.get('q')

        recipient = Recipient()
        recipient.zipcode = query
        bound_north = search.by_zipcode(recipient.zipcode).to_dict()["bounds_north"] 
        if bound_north == None:
            return None
        bound_south = search.by_zipcode(recipient.zipcode).to_dict()["bounds_south"] 
        bound_west = search.by_zipcode(recipient.zipcode).to_dict()["bounds_west"]
        bound_east = search.by_zipcode(recipient.zipcode).to_dict()["bounds_east"]
         
        recipient.latitude = (bound_north + bound_south)/2
        recipient.longitude = (bound_west + bound_east)/2
        recipient.save()

        object_list = Donor.objects.filter(
            Q(zipcode__icontains=query)
        )
        return object_list

class AboutView(generic.TemplateView):
    template_name = 'notp/about.html'

class MoreItemsView(generic.TemplateView):
    template_name = 'notp/moreitems.html'

def form(request):
    if request.method == 'POST':
        donor = Donor()
        donor.name = request.POST.get('name')
        donor.email = request.POST.get('email')
        donor.zipcode = request.POST.get('zipcode')
        bound_north = search.by_zipcode(donor.zipcode).to_dict()["bounds_north"] 
        if bound_north == None:
            return render(request, 'notp/form.html')
        bound_south = search.by_zipcode(donor.zipcode).to_dict()["bounds_south"] 
        bound_west = search.by_zipcode(donor.zipcode).to_dict()["bounds_west"]
        bound_east = search.by_zipcode(donor.zipcode).to_dict()["bounds_east"]
        donor.latitude = (bound_north + bound_south)/2
        donor.longitude = (bound_west + bound_east)/2
        donor.save()
        return render(request, 'notp/form.html')
    else:
        return render(request, 'notp/form.html')



 

mysite/notp/templates/notp/about.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>NoTp | Need a roll of toilet paper?</title>
        <link rel="stylesheet" type="text/css" href="{% static 'notp/style.css' %}">
        <link rel="icon" href="{% static 'notp/roll.png' %}"
    </head>
    <body>
        <div class="top">
            <ul class="menu">
                <li class="logo"><a href="{% url 'notp:index' %}">No<b>Tp</b></a></li>
                <li class="links"><a class="moreitems" href="{% url 'notp:moreitems' %}">More Items</a></li>
                <li class="links"><a class="about" href="{% url 'notp:about' %}">About</a></li>
                <li class="donors" style="float:right"><a class="donors" href="{% url 'notp:form' %}">Donors</a></li>
            </ul>
        </div>

        <div class="main">
            <div class="soon">
                Coming soon!
            </div>
        </div>
        
        <div class="bottom"></div>
            
    </body>
</html>

mysite/notp/templates/notp/detail.html
<h2>{{ donor.name }}</h2>
{{ donor.phone }}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'welcome:points' donor.id %}" method="POST">
{% csrf_token %}
{% for recipient in donor.recipient_set.all %}
    <input type="radio" name="recipient" id="recipient{{ forloop.counter }}" value="{{ recipient.id }}">
    <label for="choice{{ forloop.counter }}"> {{ recipient.name }}</label>
<br>
{% endfor %}
<input type="submit" value="Submit">
</form>

mysite/notp/templates/notp/form.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>NoTp | Need a roll of toilet paper?</title>
        <link rel="stylesheet" type="text/css" href="{% static 'notp/style.css' %}">
        <link rel="icon" href="{% static 'notp/roll.png' %}"
    </head>
    <body>
        <div class="top">
            <ul class="menu">
                <li class="logo"><a href="{% url 'notp:index' %}">No<b>Tp</b></a></li>
                <li class="links"><a class="moreitems" href="{% url 'notp:moreitems' %}">More Items</a></li>
                <li class="links"><a class="about" href="{% url 'notp:about' %}">About</a></li>
                <li class="donors" style="float:right"><a class="donors" href="{% url 'notp:form' %}">Donors</a></li>
            </ul>
        </div>

        <div class="main">

            <form class="form" action="" method="POST">
                <div class="text">
                    Donate today! 
                </div>
                <br>

                {% csrf_token %}
                <input class="form" type="text" name="name" placeholder="Name">
                <br>
                <input class="form" type="text" name="email" placeholder="Email">
                <br>
                <input class="form" type="text" name="zipcode" placeholder="Zip Code">
                <br>
                <input class="form" type="submit" value="Submit!">
        
            </form>
        </div>
        
        <div class="bottom"></div>
            
    </body>
</html>

mysite/notp/templates/notp/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>NoTp | Need a roll of toilet paper?</title>
        <link rel="stylesheet" type="text/css" href="{% static 'notp/style.css' %}">
        <link rel="icon" href="{% static 'notp/roll.png' %}"
    </head>
    <body>
        <div class="top">
            <ul class="menu">
                <li class="logo"><a href="{% url 'notp:index' %}">No<b>Tp</b></a></li>
                <li class="links"><a class="moreitems" href="{% url 'notp:moreitems' %}">More Items</a></li>
                <li class="links"><a class="about" href="{% url 'notp:about' %}">About</a></li>
                <li class="donors" style="float:right"><a class="donors" href="{% url 'notp:form' %}">Donors</a></li>
            </ul>
        </div>

        <div class="main">
            <div class="title">
                <div class="titletext">
                    Need a roll of
                    <br>
                    <b>toilet paper?</b> 
                    <form action="{% url 'notp:searchresult' %}" method="GET">
                        <input name="q" type="text" placeholder="Enter your zip code">
                        <input type="submit" value="Find a roll"></input>
                    </form>
                </div>
                <div class="logo">
                    <img src="{% static 'notp/roll.png' %}" alt="logo" height="450" width="270">
                </div>
            </div>
        </div>
        
        <div class="bottom"></div>
            
    </body>
</html>

mysite/notp/templates/notp/moreitems.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>NoTp | Need a roll of toilet paper?</title>
        <link rel="stylesheet" type="text/css" href="{% static 'notp/style.css' %}">
        <link rel="icon" href="{% static 'notp/roll.png' %}"
    </head>
    <body>
        <div class="top">
            <ul class="menu">
                <li class="logo"><a href="{% url 'notp:index' %}">No<b>Tp</b></a></li>
                <li class="links"><a class="moreitems" href="{% url 'notp:moreitems' %}">More Items</a></li>
                <li class="links"><a class="about" href="{% url 'notp:about' %}">About</a></li>
                <li class="donors" style="float:right"><a class="donors" href="{% url 'notp:form' %}">Donors</a></li>
            </ul>
        </div>

        <div class="main">
            <div class="soon">
                Coming soon!
            </div>
        </div>
        
        <div class="bottom"></div>
            
    </body>
</html>

mysite/notp/templates/notp/results.html
<h1>{{ donor.name }}</h1>

<ul>
    {% for recipient in donor.recipient_set.all %}
    <li>{{ recipient.name }} -- {{ recipient.request}} inches</li>
    {% endfor %}
</ul>

<a href="{% url 'welcome:detail' donor.id %}">Choose again?</a>

mysite/notp/templates/notp/search.html
<h1>This is the search page.</h1>

<form action="{% url 'welcome:searchresult' 1%}" method = "POST">
    {% csrf_token %}
    <label for="search nearby">Donor ID</label>
    <input type="search" id="search nearby" name="search nearby" value="{{ donor.id }}">
    <input type="submit" value="search">
</form>

mysite/notp/templates/notp/searchresult.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>NoTp | Need a roll of toilet paper?</title>
        <link rel="stylesheet" type="text/css" href="{% static 'notp/style.css' %}">
        <link rel="icon" href="{% static 'notp/roll.png' %}"
    </head>
    <body>
        <div class="top">
            <ul class="menu">
                <li class="logo"><a href="{% url 'notp:index' %}">No<b>Tp</b></a></li>
                <li class="links"><a class="moreitems" href="{% url 'notp:moreitems' %}">More Items</a></li>
                <li class="links"><a class="about" href="{% url 'notp:about' %}">About</a></li>
                <li class="donors" style="float:right"><a class="donors" href="{% url 'notp:form' %}">Donors</a></li>
            </ul>
        </div>

        <div class="main">
            <div class="soon">
                {% if object_list %}
                        <ul>
                        {% for donor in object_list %}
                            <li>{{ donor.name }}: {{ donor.email }}</li>
                            <br>
                        {% endfor %}
                        </ul>
                        {% else %}
                            <p>No donors are available.</p>
                        {% endif %}
            </div>
        </div>
        
        <div class="bottom"></div>
            
    </body>
</html>

mysite/welcome/templates/welcome/searchresult.html
<h1>This is the search result page.</h1>

{% if object_list %}
    <ul>
    {% for donor in object_list %}
        <li>{{ donor.name }}, {{ donor.points }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No donors are available.</p>
{% endif %}